### ISSUE TITLE
PoC Deno -> WASM -> Python Library

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#32]
Create a Proof of Concept with a trivial example that takes a Deno package, compiles it to WASM, and uses that WASM module in a Python library.

## Phase I

- [ ] Create trivial Deno package that exports several functions and classes
- [ ] Convert the package to JavaScript using Deno to Node [dnt ](https://deno.land/manual/node/dnt)
- [ ] Convert the JavaScript code to WASM using [Javy](https://www.wasm.builders/gunjan_0307/compiling-javascript-to-wasm-34lk) (or something equilavent)
- [ ] Test running WASM package

## Phase II

- [ ] Create a trivial Python app that uses [wasmer](https://wasmer.io/) to run the Deno wasm file
- [ ] Create a trivial Python library that imports and re-exports a function from the Deno wasm file 
- [ ] Publish the Python WASM wrapper library
- [ ] Try to use the Python WASM wrapper library in a Python app

## Phase III

- [ ] Create unit tests for the Python WASM wrapper library

## Phase IV

- [ ] Create a Pre Publish GitHub Action to create the WASM, wrap it in Python, and run tests
- [ ] Create a Publish GitHub Action to publish the WASM Python wrapper
